[package]
name = "gba"
version = "0.1.0"
authors = ["James Munns <james.munns@gmail.com>"]

[dependencies]
arm-code = {path = "./arm-code"}
thumb-code = {path = "./thumb-code"}

[build]
target = "???"